# Site settings
title: Dileep Shukla
email: dileepshukla901@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   I build Machine Learning solutions. Master and Bachelor of Technology from Indian Institute of Technology, Kharagpur (IIT Kgp).
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
production_url:
github_username: dileepshukla901
permalink: /blog/:year/:month/:title.html

twitter:
  username: dileepshukla901

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
