- position: B‑Certificate recipient
  at: National Cadet Corps
  url: https://indiancc.mygov.in/
- position: State Certificate
  at: Bharat Scout and Guide
  url: https://www.bsgindia.org/
- position: Organizer
  at: Blood Donation Camp at Kharagpur Blood Connect
  url: https://www.bsgindia.org/